//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.Cloud.Marketplace.App.Github.Pdf.Exporter.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.Cloud.Marketplace.App.Github.Pdf.Exporter.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;zen&quot;: &quot;Practicality beats purity.&quot;,
        ///    &quot;hook_id&quot;: 197322517,
        ///    &quot;hook&quot;: {
        ///        &quot;type&quot;: &quot;Repository&quot;,
        ///        &quot;id&quot;: 12345678,
        ///        &quot;name&quot;: &quot;web&quot;,
        ///        &quot;active&quot;: true,
        ///        &quot;events&quot;: [
        ///            &quot;push&quot;,
        ///            &quot;pull_request&quot;
        ///        ],
        ///        &quot;config&quot;: {
        ///            &quot;content_type&quot;: &quot;json&quot;,
        ///            &quot;insecure_ssl&quot;: &quot;0&quot;,
        ///            &quot;url&quot;: &quot;https://example.com/webhook&quot;
        ///        },
        ///        &quot;updated_at&quot;: &quot;2019-06-03T00:57:16Z&quot;,
        ///        &quot;created_at&quot;: &quot;2019-06-03T00: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Github_Webhook_ping {
            get {
                return ResourceManager.GetString("Github_Webhook_ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;action&quot;:&quot;purchased&quot;,
        ///   &quot;effective_date&quot;:&quot;2020-04-01T00:00:00+00:00&quot;,
        ///   &quot;sender&quot;:{
        ///      &quot;login&quot;:&quot;sender-username&quot;,
        ///      &quot;id&quot;:3877742,
        ///      &quot;avatar_url&quot;:&quot;https://avatars2.githubusercontent.com/u/3877742?v=4&quot;,
        ///      &quot;gravatar_id&quot;:&quot;&quot;,
        ///      &quot;url&quot;:&quot;https://api.github.com/users/username&quot;,
        ///      &quot;html_url&quot;:&quot;https://github.com/username&quot;,
        ///      &quot;followers_url&quot;:&quot;https://api.github.com/users/username/followers&quot;,
        ///      &quot;following_url&quot;:&quot;https://api.github.com/users/username/following{/other_user}&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Github_Webhook_purchased {
            get {
                return ResourceManager.GetString("Github_Webhook_purchased", resourceCulture);
            }
        }
    }
}
